export default function QuizzesPage() {
  return (
    <>
      <h1 className="text-4xl font-bold text-heading">
        Quizzes
      </h1>

      <p className="mt-2 text-muted">
        Practice quizzes generated by Iris.
      </p>
    </>
  );
}